### PR TITLE
Issue243

### PR DESCRIPTION
**Pull request by j0rt3g4**
Solving #243

### CODE REVIEW

**Comment by mypil** [comment]
@dianef77 - can you please assist to approve and merge the content for this PR based on issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/243?

Thanks.

**Comment by mypil** [comment]
@dianef77 - I would like to follow up on this. Can you possibly approve and merge the content for this PR so we can close issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/243?

Thank you.

**Comment by mypil** [comment]
@dianef77 - I would like to follow up on this.  Kindly approve and merge the content for this PR so we can close issue #243 

Thank you.

**Comment by mypil** [comment]
@dianef77 - I would like to follow up on this. Can you possibly approve and merge the content for this PR so we can close issue #243?

Thank you.

**Comment by j0rt3g4** [comment]
Thank you @dianef77

**Pull request merged**
