### PR TITLE
Update release-options-in-office-365.md

### PR DESCRIPTION
**Pull request by nenonix**
Updated roadmap reference and link, fixed link to Message Center and added note re permissions as per https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/214

### CODE REVIEW

**Comment by mypil** [comment]
Hi @Sirkkuw - can you please assist to approve and merge the data for this PR based on issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/214

**Comment by mypil** [comment]
@Sirkkuw - We would like to follow up on this request for approval to merge content for PR based on issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/214

**Comment by nenonix** [comment]
@mypil @Sirkkuw, Apologies -  I  should have noticed that the content in question occurs twice with the same information  repeated close to the the start and then again at the end of the document.   I only corrected the first instance. To avoid redundancy I will also address (remove) the repetition in a new commit.

**Comment by mypil** [comment]
@Sirkkuw - Can you possibly check if the content can be merged for this PR or if there's still a need to edit it further? Please advise.

Thank you.

**Comment by Sirkkuw** [comment]
done

**Pull request merged**
