### PR TITLE
Dariomws1

### PR DESCRIPTION
**Pull request by dariomws306**
You cannot pipe Add-MailboxPermission after Set-Mailbox. Set-Mailbox doesn't have output so Add-MailboxPermission won't apply:
https://docs.microsoft.com/en-us/exchange/client-developer/management/exchange-management-shell-cmdlet-input-and-output-types

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@SuPotter Can I merge this?

**Comment by mypil** [comment]
Hi @dianef77 - can you please assist to approve and merge the content for this PR based on issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/100?

Thanks.

**Comment by mypil** [comment]
@dianef77 - I would like to follow up on this. Can you possibly approve and merge the content for this PR so we can close issue #100?

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - This PR can be closed. Thank you.

**Pull request merged**
