### PR TITLE
Typo Correction issue #555

### PR DESCRIPTION
**Pull request by j0rt3g4**
Correction TOC.md typo. Related to Issue #555

### CODE REVIEW

**Comment by j0rt3g4** [comment]
Resolving Issue #555

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@Sirkkuw - Can you please assist to check, approve and merge the content of this PR based on issue #555?

Thank you.

**Comment by mypil** [comment]
@Sirkkuw - We would like to follow up. Can you please assist to check, approve and merge the content of this PR based on issue #555?

Thank you.

**Comment by Sirkkuw** [comment]
I have approved this.

**Pull request merged**
