### PR TITLE
Update get-access-to-and-back-up-a-former-user-s-data.md

### PR DESCRIPTION
**Pull request by msbemba**

### CODE REVIEW

**Comment by msbemba** [comment]
Create PR with a note added about size limit and file versioning in Onedrive.

**Comment by mypil** [comment]
@twernermsft - can you please assist to approve and merge the data for this PR based on issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/163

**Comment by mypil** [comment]
@twernermsft - I would like to follow up on this. Can you please assist to approve and merge the content for this PR based on issue #163?

Thank you.

**Comment by mypil** [comment]
@twernermsft - I would like to follow up on this. Can you please assist to approve and merge the content for this PR based on issue #163?

Thank you.

**Comment by mypil** [comment]
@twernermsft - I would like to follow up on this. Can you please assist to approve and merge the content for this PR based on issue #163?

Thank you.

**Pull request merged**
