### PR TITLE
Update regional-availability.md

### PR DESCRIPTION
**Pull request by nitinjms2**

### CODE REVIEW

**Comment by nitinjms2** [comment]
Please approve the PR as Kaizala availability is worldwide, except certain countries

**Comment by mypil** [comment]
@chuckedmonson - Can you please assist to check, approve and merge the content of this PR?

Thank you.

**Comment by nitinjms2** [comment]
Chuck is on leave and we need to do this soon, as customers are seeing different info for Kaizala availability at different marketing/doc assets

**Comment by mypil** [comment]
@cmcatee-MSFT @AndreaBarr - are you able to merge this in behalf of @chuckedmonson? Thank you.

**Comment by cmcatee-MSFT** [comment]
@AndreaBarr I'm currently trying to verify the information.

**Pull request merged**
