### PR TITLE
Made OneDrive reference more concise

### PR DESCRIPTION
**Pull request by gacarini**
I realized the Mac and Windows references for the OneDrive Sync Client were a bit repetitive. I've merged them to make the section a bit more concise.

### CODE REVIEW

**Comment by gacarini** [comment]
@kaarins as well to take a look to see if I referred to everything correctly.

**Comment by mypil** [comment]
@Sirkkuw - can you please assist to approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@Sirkkuw - I would like to follow up on this. Can you please assist to approve and merge the content for this PR?

Thank you.

**Comment by Sirkkuw** [comment]
@mypil  - done.

**Pull request merged**
