### PR TITLE
Update integrated-apps.md

### PR DESCRIPTION
**Pull request by nenonix**
lines 33 and 57 - pronouns edited. fixes https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/387

### CODE REVIEW

**Comment by dianef77** [comment]
Leave his and her as their, and the fwlink needs to be done like this: http://go.microsoft.com/fwlink/p/?LinkID=518600

**Comment by mypil** [comment]
@dianef77 - should @nenonix create another PR for this following your recommended changes? Please advise how to proceed. Thank you.

**Comment by dianef77** [comment]
Sorry I closed this one.  You can make your changes and use this pr, I think.

**Comment by mypil** [comment]
@nenonix - kindly apply the recommended changes on this PR as indicated by @dianef77. Thank you.

**Comment by nenonix** [comment]
@dianef77 changes have been made, Thank you

**Pull request merged**
