### PR TITLE
Update enable-usage-analytics.md

### PR DESCRIPTION
**Pull request by nenonix**
Changes made as per https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/177

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@SuPotter Can I merge this?

**Comment by mypil** [comment]
Hi @Sirkkuw - can you please assist to approve and merge the data for this PR based on issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/177

**Comment by mypil** [comment]
@Sirkkuw - I would like to follow up on this. Can you possibly approve and merge the content for this PR so we close issue #177? Thanks.

**Comment by Sirkkuw** [comment]
The topic is actually correct for setting up. I am going to close this PR.

**Pull request closed without merging**
