### PR TITLE
Revoke Permission from user's one drive

### PR DESCRIPTION
**Pull request by npsptechusa**
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/115

### CODE REVIEW

**Comment by mypil** [comment]
@twernermsft - can you please assist to check, approve and merge the content for this PR based on issue #115?

Thank you.

**Comment by mypil** [comment]
@twernermsft -  I would like to follow up on this. Please assist to check, approve and merge the content for this PR based on issue #115 
Thanks.

**Comment by mypil** [comment]
@AndreaBarr @kenwith - would you be able to merge the content for this PR based on issue #115?

**Comment by AndreaBarr** [comment]
@SuPotter  can you approve this for merging please?

**Comment by mypil** [comment]
@kenwith - would you be able to merge the content for this PR? Thanks.

**Comment by kenwith** [comment]
Please adjust PR to break out the step on removing access (after it was gained in the current procedure) into a separate step-by-step procedure in the article. So instead of Step 6, add another section immediately after that is on removing access. Also, please provide more details. The current PR tells you to go to user profiles but doesn’t tell you where to go from there, how to find the profile, etc.

**Comment by mypil** [comment]
@npsptechusa - please take note of the comment above and kindly make the necessary changes to the PR. Thank you.

**Pull request closed without merging**
