### PR TITLE
Update manage-creation-of-groups.md

### PR DESCRIPTION
**Pull request by TeresaFG-writer**
Content change request by Corrie Cason has been implemented.

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@TeresaFG-writer - PR #762 appears to be a duplicate to this PR. Which of the two is the correct one? 

Please confirm and close the PR that will not be used. Thank you.

**Comment by mypil** [comment]
@MikePlumleyMSFT - PR has been copy edited and is ready for final review.

Thank you.

cc: @kenwith

**Comment by TeresaFG-writer** [comment]
I'm curious what is the ETA on publishing live? Does Yammer and Office have an SLA on this type of work? I ask because I'm trying to give Yammer a reliable schedule or turnaround time for when they can expect to see changes to documents once I submit.

**Pull request merged**
