### PR TITLE
Update domains-faq.md

### PR DESCRIPTION
**Pull request by nenonix**
Edited lines 420 and 422 for clarity as per https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/324

### CODE REVIEW

**Comment by mypil** [comment]
@pebaum - can you please assist to check, approve and merge the content for this PR based on issue #324?

Thank you.

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #324?

Thank you.

**Comment by nenonix** [comment]
see https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/334 as
well. duplicate issue

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #324 and #334?

cc: @kenwith @AndreaBarr

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #324 and #334?

**Pull request merged**
