### PR TITLE
Fixing Issue #169

### PR DESCRIPTION
**Pull request by j0rt3g4**
This PR solves issue #169 
* Added more information and a better way to read the Cmdlets of multiple lines
* Added the correct way to check if a module exists or if it's not
* Added 2 reports of the users with the passwordsNeverExpire attribute as CSV and as HTML.
* Added an Image of how to use Powershell v5 and Nuget gallery to install a specific Module in this case AzureAD.
* Preserved edits from @nenonix , If you want to add anything let me know.
* Removed the reference to the AzureAD reference since that documentation is plain bad, It doesn't explain at all how to install the module that's the reason why I did it separately on this PR.

* Please go to https://docs.microsoft.com/en-us/powershell/module/Azuread/?view=azureadps-2.0 and try to understand something, how is that related to how to install a module?, specific to the AzureAD module.

### CODE REVIEW

**Comment by mypil** [comment]
@dianef77 - can you please assist to check, approve and merge the content for this PR based on issue #169  ?

Thank you.

**Comment by mypil** [comment]
@dianef77 - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #169 ?

Thank you.

**Comment by dianef77** [comment]
Hi, please polish the writing so it follows our guidelines. For example, "With," "Report," and "Cmdlet" should be lowercase.  End of sentence needs a period or colon, depending on whether it's introducing a step. We use "Run" instead of "Execute."

**Comment by kenwith** [comment]
@dianef77 - the coordinator on this one, @mypil , is going to get a copy edit for you and is also taking this knowledge back to others coordinating repositories so we can catch copy edit needs before they get to you. Thanks for your patience as we get this worked out!

**Pull request closed without merging**
