### PR TITLE
Update create-dns-records-at-cloudflare.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the number of CName records

### CODE REVIEW

**Comment by msbemba** [comment]
Issue # https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/929

**Comment by mypil** [comment]
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@msbemba - please check and add in the suggested changes from @JohanFreelancer9 for line 169 as applicable. Kindly validate and review. Thank you.

**Comment by msbemba** [comment]
> @msbemba - please check and add in the suggested changes from @JohanFreelancer9 for line 169 as applicable. Kindly validate and review. Thank you.

Made the changes as per the suggestion.

**Comment by mypil** [comment]
@pebaum - PR has been copy edited and is ready for final review. This is based on issue #929

Thank you.

cc: @kenwith

**Pull request merged**
