### PR TITLE
Update Revoke Permission

### PR DESCRIPTION
**Pull request by npsptechusa**
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/115

### CODE REVIEW

**Comment by mypil** [comment]
@twernermsft - can you please assist to check, approve and merge the content for this PR based on issue #115?

Thank you.

**Comment by mypil** [comment]
@twernermsft - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #115?

Thank you.

**Comment by twernermsft** [comment]
I don’t see that action on this one.

**Comment by mypil** [comment]
@twernermsft - I believe he added some information in the article specific to the revoke permission- https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/280/files

**Comment by mypil** [comment]
@twernermsft - I would like to follow up on this. Please assist to check again and merge content. Thank you.

**Comment by mypil** [comment]
@npsptechusa - please check on this, the doc author could not see the changes you made. Could it be because it shows- 	"npsptechusa wants to merge 1 commit into MicrosoftDocs:public from unknown repository"? Which repository is this supposed to be? Please make the necessary changes. Thanks.

**Pull request closed without merging**
