### PR TITLE
Update CNAME Record

### PR DESCRIPTION
**Pull request by npsptechusa**
Issue Url- 
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/268

Replaced enterpriseenrollment.manage.microsoft.com with enterpriseenrollment-s.manage.microsoft.com

### CODE REVIEW

**Comment by mypil** [comment]
@AndreaBarr @kenwith - this is for a level 1 complexity issue. Can you please assist to approve and merge the content for this PR based on issue #268 ?

Thank you.

**Comment by kenwith** [comment]
This is changing the domain and adding a '-s' into the domain. I think we need @pebaum to confirm on this article he owns so he can confirm.

**Comment by mypil** [comment]
@pebaum - can you please assist to check, approve and merge the content for this PR based on issue
#268 ?

Thank you.

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. can you please assist to check, approve and merge the content for this PR based on issue#268 ?

Thank you.

**Comment by pebaum** [comment]
closing without merging. I fixed this in multiple places in a parallel pull.

**Pull request closed without merging**
