### PR TITLE
Formatting improvements

### PR DESCRIPTION
**Pull request by adrianwells**
Related to Buy a domain redirects to a Microsoft's partner page #462

### CODE REVIEW

**Comment by mypil** [comment]
@pebaum @dianef77 - Can you please assist to check, approve and merge the content for this PR based on issue #462?

Thank you.

**Comment by dianef77** [comment]
Please lowercase purchase/managed.

**Comment by adrianwells** [comment]
@dianef77 done, fyi @mypil

**Comment by mypil** [comment]
There was a typo for the word purchased so created PR #473 to correct this.

**Pull request merged**
