### PR TITLE
Update get-access-to-and-back-up-a-former-user-s-data.md

### PR DESCRIPTION
**Pull request by dariomws306**

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@SuPotter Can I merge this?

**Comment by mypil** [comment]
@twernermsft - can you please assist to approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@twernermsft - I would like to follow up on this. Can you please assist to approve and merge the content for this PR?

Thank you.

**Comment by mypil** [comment]
@twernermsft - I would like to follow up on this. Can you please assist to approve and merge the content for this PR?

Thank you.

**Pull request merged**
