### PR TITLE
Dariomws3

### PR DESCRIPTION
**Pull request by dariomws306**
I have added a note to let readers know that they need certain office 2013 version to enable ADAL. Also I have added the "plan ADAL" article to the last secion (Related articles).

### CODE REVIEW

**Comment by kenwith** [comment]
@Sirkkuw does this look good to merge?

**Comment by dianef77** [comment]
Please have a copy editor review.

**Comment by kenwith** [comment]
@mypil - for copy edit review. We have a new process to get copy edit on all PR so this will be a good test case. @mypil - the copy editor can click Files Changed and then on each line click the Plus sign on left and it will pop open a suggested changes box.. there is a button at top to Suggest Change.. and then @dariomws306 can approve the change back into the PR. Should be simple and it is a brand new feature of GitHub we can try out. Let me know if any questions and we can walk through first one together too.

**Comment by kenwith** [comment]
@dariomws306 - I am doing a bit of a test as this is new. Do you see something in this PR that you can commit or approve?

**Comment by dariomws306** [comment]
@kenwith , I have a "Commit Suggestion" button. Should I press it?

**Comment by dariomws306** [comment]
Also, there is a "Resolver Conversation" button.

**Comment by kenwith** [comment]
Yes, go for it let's see what happens and hope the repo doesn't implode. 👍

**Comment by dariomws306** [comment]
done!

**Comment by kenwith** [comment]
Perfect!  See the changes I put in the PR now so it should work well for copy edits and other edits when we need review of PR and the only person that can commit the suggestion to the PR is the person that originally opened the PR.. so that maintains sanity

**Comment by mypil** [comment]
@TokyoScarab - FYI. Here's a sample of the copy edit review done by Ken for your reference. Thanks.

**Comment by Sirkkuw** [comment]
@kenwith - looks fine.

**Pull request merged**
