### PR TITLE
Update auto-acceleration-policy-for-signing-in.md

### PR DESCRIPTION
**Pull request by robertofan**
To retrieve the servicePrincipal for the Yammer application, the parameter -All must be used when invoking Get-AzureADServicePrincipal

### CODE REVIEW

**Comment by mypil** [comment]
@get-itips - As discussed, please assist with the PS review for this PR.

Thank you.

**Comment by get-itips** [comment]
Hello @robertofan 
Thanks for your contribution.
I see this as a good addition as  `Get-AzureADServicePrincipal` returns only the first 100 objects without the `-All:$true` and chances are, that the Yammer Service Principal object not getting into this list (in my demo lab it was listed on the first 100 but I'll accept the change anyway)

Thank you

**Comment by mypil** [comment]
@TeresaFG-writer - PS review for this PR has been done.  PR is ready for final review. 

Thank you.

cc: @kenwith

**Comment by mypil** [comment]
@TeresaFG-writer - We would like to follow up. Can you please assist to review and merge this PR?
@pamgreen - Would you be able to help merge this PR?

Thank you.

**Comment by TeresaFG-writer** [comment]
Hi Joyce,

I’m not seeing this exact one that you reference in the Subject line however, there are others that are open because I’m waiting for SME signoff. Should happen tomorrow. They were all in an all-day offsite on Friday so I got no response.

~Teresa

**Comment by TeresaFG-writer** [comment]
Waiting for approval by Adam Peretz who is back in the office on Monday.

**Pull request merged**
