### PR TITLE
Completed: Step 2 8b incorrect #248

### PR DESCRIPTION
**Pull request by RussC19**
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/248

### CODE REVIEW

**Comment by mypil** [comment]
@IrenePasternack - can you please assist to approve and merge the data for this PR based on issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/248

**Comment by mypil** [comment]
@IrenePasternack - I would like to follow up on this. Can you please assist to approve and merge the content for this PR based on issue #248?

Thank you.

**Comment by IrenePasternack** [comment]
I have fixed this and republished the article.

**Comment by AndreaBarr** [comment]
@IrenePasternack  Thank you for fixing the article. I will close this PR then.

**Pull request closed without merging**
