### PR TITLE
Update Credit Card Issuing Country Info

### PR DESCRIPTION
**Pull request by npsptechusa**
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/96

### CODE REVIEW

**Comment by mypil** [comment]
@cmcatee-MSFT - can you please assist to check, approve and merge the content for this PR based on issuehttps://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/96?

Thank you.

**Comment by mypil** [comment]
@cmcatee-MSFT - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #96?

Thank you.

**Comment by mypil** [comment]
@cmcatee-MSFT - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #96?

**Comment by mypil** [comment]
@cmcatee-MSFT  - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #96?

Thank you.

**Comment by mypil** [comment]
@cmcatee-MSFT - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #96?

Thank you.

**Comment by mypil** [comment]
@cmcatee-MSFT - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #96?

Thank you.

**Comment by cmcatee-MSFT** [comment]
@mypil - Please fix the 2 sentences to be grammatically correct English:

"You must use a credit card issued from the same country as your tenant."

PM has verified that this statement is accurate.

**Comment by mypil** [comment]
@npsptechusa - please make the recommended changes on the 2 sentences as advised above by Cern. Thank you.

**Comment by npsptechusa** [comment]
@cmcatee-MSFT Thank You Cern for your feedback. I could not update the existing PR so, closing this out.

I update document with your comments and requested new PR- https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/350

Can you please review it.

Thank You

**Pull request closed without merging**
