### PR TITLE
Issue#169+Fixes

### PR DESCRIPTION
**Pull request by j0rt3g4**
Fixes @nenonix  @AndreaBarr 
This is the corrected

### CODE REVIEW

**Comment by mypil** [comment]
@dianef77 - please assist to just check on the technical portion of this PR based on issue #169 ? I have sent you an email with the details on why we require your assistance to check on the technical content. Please do not merge the content yet but just let us know if the technical aspect of this PR is accurate Thank you.
@kenwith @nenonix -FYI.

**Comment by mypil** [comment]
@nenonix - please assist to review the content of this PR and make the necessary content edits. This is related to issue #169 

Thank you.

**Comment by mypil** [comment]
@dianef77 - the content portion has been reviewed and corrected. Can you please assist to check, approve and merge the content for this PR based on issue #169? Thank you.  

cc: @kenwith

**Comment by mypil** [comment]
@dianef77 - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #169?

Thank you.

**Comment by mypil** [comment]
@dianef77 - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #169? 

Thank you.

**Comment by kenwith** [comment]
@dianef77 - I reviewed the PowerShell and technical and this looks good. I am going to go ahead and merge and if you have any reservations let me know and we can adjust this article.

**Pull request merged**
