### PR TITLE
Update add-users.md

### PR DESCRIPTION
**Pull request by nenonix**
Added a note for clarity as per https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/80

### CODE REVIEW

**Comment by mypil** [comment]
@Sirkkuw - can you please assist to check, approve and merge the content for this PR based on issue #80?

Thank you.

**Comment by mypil** [comment]
@Sirkkuw - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #80?

Thank you.

**Comment by mypil** [comment]
@Sirkkuw - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #80? Thank you.

cc: @kenwith @AndreaBarr

**Comment by Sirkkuw** [comment]
@mypil  - I would change  "After migration you need to activate Office 365 user accounts by assigning licences" to "If you create users by migrating mail boxes, you will need to active Office 365 user accounts by assigning licenses..." And even then, this is a bit redundant with the end of the article where migration is discussed. Note that licenses was misspelled in the proposed change.

**Comment by mypil** [comment]
@nenonix - please check and make the necessary changes as recommended by @Sirkkuw. Thanks.

**Comment by nenonix** [comment]
Done. https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/pull/356

**Pull request merged**
