### PR TITLE
Fix for text formatting in record examples.

### PR DESCRIPTION
**Pull request by MikeyMJCO**
Fix incorrectly italicised, bolded text in the record examples.

### CODE REVIEW

**Comment by mypil** [comment]
@pebaum - Can you please assist to check, approve and merge the content of this PR?

Thank you.

**Comment by cmcatee-MSFT** [comment]
@MikeyMJCO If they are variables, they should only be italicised, not bold. Please fix and then I'll approve the changes. Thanks.

**Comment by mypil** [comment]
@MikeyMJCO - We would like to follow up. Kindly make the necessary changes as recommended by Cern so this PR can be merged. Thanks.

**Comment by MikeyMJCO** [comment]
Updated with a new commit to the patch-1 branch.

**Comment by mypil** [comment]
@cmcatee-MSFT - Please assist to review and merge the PR content. Thank you.

**Pull request merged**
