### PR TITLE
Corrected issue 190

### PR DESCRIPTION
**Pull request by j0rt3g4**
Correcting Issue 190 from 403 to 404

### CODE REVIEW

**Comment by mypil** [comment]
Hi @MikePlumleyMSFT can you please assist to approve and merge the data for this PR based on issue# https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/190

Thank you.

**Comment by MikePlumleyMSFT** [comment]
@mypil there are some grammar issues / typos in the updates. Can you address those?

**Comment by j0rt3g4** [comment]
I can check them if you let me know what are the issues

**Comment by MikePlumleyMSFT** [comment]
"... won't be able to this changes."

**Comment by j0rt3g4** [comment]
> "... won't be able to this changes."

These* ty

**Pull request merged**
