### PR TITLE
fixed sipprotocol missing line and additional

### PR DESCRIPTION
**Pull request by Malind19**
Saw additional issue as well and fixed that too.

### CODE REVIEW

**Comment by dianef77** [comment]
@pebaum please  review and decide whether to merge

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #415?

Thank you.

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #415?

Thank you.

cc: @mnirke

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #415?

Thank you

**Pull request merged**
