### PR TITLE
update auto-acceleration-policy-for-signing-in.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
issue #416 
removed link to outdated 'PackageManagement PowerShell Modules Preview"
added clarification for old PowerShell versions

### CODE REVIEW

**Comment by mypil** [comment]
@IrenePasternack - can you please assist to check, approve and merge the content for this PR based on issue #416?

Thank you.

**Comment by mypil** [comment]
@IrenePasternack - You commented on issue #416 that you already updated the topic and links in the article. Do we still need to keep this PR open or should I let @MaratMussabekov just close it?

Please advise on how to proceed. Thank you.

**Comment by IrenePasternack** [comment]
It is fine for MaratMussabekov to close it.

**Comment by mypil** [comment]
@MaratMussabekov - Please close this PR. Thank you.

**Pull request closed without merging**
