### PR TITLE
Updated shadow tanent admin

### PR DESCRIPTION
**Pull request by joinimran**
I have updated that no service will be impacted when a shadow tenant will be taken over.

### CODE REVIEW

**Comment by mypil** [comment]
@pebaum - can you please assist to check, approve and merge the content for this PR based on issue #298?

Thank you.

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #298?

Thank you.

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this. Can you please assist to check, approve and merge the content for this PR based on issue #298?

Thank you.

**Comment by mypil** [comment]
@kenwith @AndreaBarr - Would you be able to merge the content for this PR based on issue #298?

Thank you.

**Comment by AndreaBarr** [comment]
@SuPotter Can I merge this?

**Comment by kenwith** [comment]
It looks like @pebaum is the 'author' listed on this article.. not sure @SuPotter would be the right person to ask.

**Pull request merged**
