### PR TITLE
Update manage-deployment-of-add-ins.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to reflect the correct add-in acquisition steps

### CODE REVIEW

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@Sirkkuw - Can you please assist to check, approve and merge the content of this PR based on issue #541?

Thank you.

**Comment by mypil** [comment]
@Sirkkuw - We would like to follow up on this. Can you please assist to check, approve and merge the content of this PR based on issue #541?

Thank you.

**Comment by msbemba** [comment]
Closed as comits https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/be62de3b6a5f753e49c66c66577563ee65adb403#diff-47195a1a95c973d2900d8818b4c34f3e and https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/commit/50e080278be3157a3eb08bd5b6d62f3f85e83e13#diff-47195a1a95c973d2900d8818b4c34f3e are successfully merged and has the document upto date.

**Pull request closed without merging**
