### PR TITLE
Issue114

### PR DESCRIPTION
**Pull request by j0rt3g4**
Those changes are for synchronization from my fork into the latest version.
Resolving Issue [Issue 114](https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/114)

### CODE REVIEW

**Comment by mypil** [comment]
@Sirkkuw - can you please assist to check, approve and merge the content for this PR based on issue #114 ? 

Thank you.

**Comment by Sirkkuw** [comment]
@j0rt3g4 - can you tell me how you are associated with this documentation? I have some concerns about adding it because it is a separate subscription and would require Office 365 and Microsoft 365 business users purchase a separate plan to support this.

**Comment by j0rt3g4** [comment]
Hi @Sirkkuw I'm working with  @kenwith.
I'm a Microsoft Partner with Faru bonon IT and also I work as an independent freelancer for the  Polyglot Team (Microsoft Freelancer program with Nuri and Joana) and also I have pretty much experience with Powershell https://social.technet.microsoft.com/Profile/j0rt3g4
27.5 k download with my scripts

**Comment by Sirkkuw** [comment]
@j0rt3g4 can you take the MFA article changes out of this PR and I will accept? If you want to add the changes to the MFA topic, I would just want a short description and link to the plans. Maybe some links to their content, don't want to rewrite it.

**Comment by j0rt3g4** [comment]
I can
All those changes were done to update my forked into the Update of the public. either way, I can refork the content again and modify it

**Comment by j0rt3g4** [comment]
@Sirkkuw Done on Updates on Pull #276

**Pull request closed without merging**
