### PR TITLE
Update manage-creation-of-groups.md

### PR DESCRIPTION
**Pull request by Shelleyliu0415**
modify the content

I try to do the cmdlet running in other windows server couldn't work.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@SuPotter Can I merge this?

**Comment by Sirkkuw** [comment]
This should be for @dianef77

**Comment by mypil** [comment]
@dianef77 - can you please assist to approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@AndreaBarr - This PR can be closed. Thank you.

**Pull request merged**
