### PR TITLE
Update parameter to use with "Set-UnifiedGroup"

### PR DESCRIPTION
**Pull request by dimcry**
Update parameter to use with "Set-UnifiedGroup". We should use -EmailAddresses, instead of using -Alias, when removing an email address, from the list.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@SuPotter Can I merge this?

**Comment by mypil** [comment]
@adefowler - can you please assist to approve and merge the content for this PR? 

Thank you.

**Comment by mypil** [comment]
@adefowler - I would like to follow up on this. Can you please assist to approve and merge the content for this PR?

Thank you.

**Comment by adefowler** [comment]
I’m new to this and am following up with my coworkers to find out what I’m supposed to do. I will resolve this today. Sorry about the wait.

**Pull request merged**
