### PR TITLE
Added note for KB language

### PR DESCRIPTION
**Pull request by npsptechusa**
https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/293

### CODE REVIEW

**Comment by mypil** [comment]
@IrenePasternack - can you please assist to check, approve and merge the content for this PR based on issue #293? 

Thank you.

**Comment by mypil** [comment]
@IrenePasternack - I would like to follow up on this. Please assist to check, approve and merge the content for this PR based on issue #293 

Thank you.

**Comment by mypil** [comment]
@IrenePasternack - I would like to follow up on this. Please assist to check, approve and merge the content for this PR based on issue #293

Thank you.

**Comment by mypil** [comment]
@AndreaBarr @kenwith - Can you possibly assist to merge the content for this PR based on issue #293?

**Comment by kenwith** [comment]
Looks good.

**Pull request merged**
