### PR TITLE
Update get-access-to-and-back-up-a-former-user-s-data.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
clarify which admin center need to be used

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
issue #600

**Comment by mypil** [comment]
@nenonix @JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks.

**Comment by mypil** [comment]
@twernermsft @cmcatee-MSFT @aruhdam - PR has been copy edited and is ready for final review. This is based on issue #600. Looping in Cern and Madhura in this PR since I am not sure if Tom is still the doc owner for this document content.

Thank you.

cc: @kenwith @AndreaBarr

**Comment by cmcatee-MSFT** [comment]
Change is not needed. Article is correct as written. We no longer use the "Office 365" or "Microsoft 365" designation when talking about the main admin center. Note that "admin center" is NOT capitalized.

**Pull request closed without merging**
