### PR TITLE
Update O365 subscription info

### PR DESCRIPTION
**Pull request by khorne3**
Addresses https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/156.

### CODE REVIEW

**Comment by AndreaBarr** [comment]
@SuPotter Can I merge this?

**Comment by mypil** [comment]
@pebaum - can you please assist to approve and merge the content for this PR based on issue https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro/issues/156? 

Thank you.

**Comment by mypil** [comment]
@pebaum - I would like to follow up on this.  Can you please assist to approve and merge the content for this PR based on issue #156?

Thank you.

**Comment by pebaum** [comment]
The correction offered here creates more confusion. I will add something here as an alternative.

**Comment by mypil** [comment]
@pebaum - may we know what has been added or is there another MS article that we have to redirect the requester to? Please advise. Thank you.

**Comment by marypcbuk** [comment]
hi; I opened the original issue and the proposed change would be exactly what people ask me about this topic; they want to know what O365 subscriptions can have custom domains and whether they can get them on non-business Office 365 subs. I'd vote for merging this content (unless you want to add something that has the same information but avoids whatever confusion you're concerned about)

**Comment by mypil** [comment]
@pebaum - please assist to check on the requester's feedback and advise on the next action for this. Thank you.

**Pull request closed without merging**
