### PR TITLE
Update release-options-in-office-365.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the note

### CODE REVIEW

**Comment by mypil** [comment]
@Sirkkuw - Can you please assist to check, approve and merge the content of this PR based on issue #565?

Thank you.

**Comment by cmcatee-MSFT** [comment]
@Sirkkuw Please review. Is "Office 365 Suites" a legitimate way to refer to the product?

**Comment by msbemba** [comment]
@cmcatee-MSFT  @Sirkkuw The releases would affect the office 365 suite (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-suite-features) So I think it is the right way to call it.

**Comment by cmcatee-MSFT** [comment]
@msbemba There is no product called "Office 365 Suite". I think the confusion is coming from the capitalization of the service description article. Therefore, the article is correct as currently written.

**Pull request closed without merging**
